### ISSUE TITLE
Remove @contentful/rich-text-types dependency in output

### ISSUE THREAD

**Issue by marcolink** [contentful-userland/cf-content-types-generator#10]
[RichText](https://github.com/contentful/contentful.js/blob/master/index.d.ts#L224) type from `contentful` types should be sufficient.

**Comment by AndrewLeedham** [comment]
I was about to raise an issue to change https://github.com/contentful-labs/cf-content-types-generator/blob/master/src/renderer/cf-render-prop.ts#L10 to just use `CFRichTextTypes.Document`, but I think this would fix that as well.
