### ISSUE TITLE
Rendering of link arrays incorrect

### ISSUE THREAD

**Issue by phawxby** [contentful-userland/cf-content-types-generator#127]
https://github.com/contentful-labs/cf-content-types-generator/blob/master/src/renderer/cf-render-prop-array.ts#L13

Should be something more like this.
```
  return `(${renderPropLink(field.items)})[]`;
```

We've fixed it in our library fork but due to numerous other customisation in our fork it's not so easy to just generate a fix PR. 

Before: `pages?: EntryLink<PageCMSEntry> | EntryLink<ComponentCardCMSEntry>[];`
After: `pages?: (EntryLink<PageCMSEntry> | EntryLink<ComponentCardCMSEntry>)[];`

**Comment by marcolink** [comment]
Hi @phawxby 👋 
Thanks for reporting this.

I'm currently working on a completely customizable renderer #123  - I wonder if this would help with your customization.
Would love to get some feedback on this 😎

**Comment by phawxby** [comment]
@AndrewLeedham was responsible for our customisations, he's probably the best person to speak to that.

**Comment by marcolink** [comment]
Thanks @phawxby,

And btw, this fix here is already part of the PR!

**Comment by AndrewLeedham** [comment]
Yup on my to-do list 👍

**Comment by marcolink** [comment]
released with 2.0.0
