### ISSUE TITLE
How to correctly format CreateEntryProps with Link<Entry>

### ISSUE THREAD

**Issue by yan-kisen** [contentful-userland/cf-content-types-generator#138]
How can we leverage this Type definition to construct Entry Fields object?

**Simplified Example:**

```typescript
export interface TypeMediaFields {
    type: "Audio" | "Video" | "Photo" ;
    homeArticle?: Contentful.Entry<TypeArticle>;
}

export type TypeMedia = Contentful.Entry<TypeMediaFields>;

export interface TypeArticleFields {
  articleKey?: Contentful.EntryFields.Symbol;
  type: 'Encyclopedia' | 'Special Report';
}
```

```typescript
async function formatCreateMediaEntryFields(item: ExistDbMediaRecord): Promise<Partial<TypeMediaFields>> {
return {
    homeArticle: formatEntryLink(await resolveEntryIdByLegacyKey(item.homeArticleKey, CONTENT_TYPES.ARTICLE)),
    slugline: item.slugline,
  }  as TypeMediaFields;
}


function formatEntryLink(entryId: string): Link<'Entry'> {
  return {
    sys: {
      type: 'Link',
      linkType: 'Entry',
      id: entryId,
    },
  };
}
```

Typescript is giving the following message:

>  Conversion of type `'{ homeArticle: Link<"Entry">; slugline: string; }'` to type `'TypeMediaFields'` may be a mistake because neither type sufficiently overlaps with the other. If this was intentional, convert the expression to 'unknown' first.   Property `'type'` is missing in type `'{ homeArticle: Link<"Entry">; slugline: string; }'` but required in type `'TypeMediaFields'`.

Why should I need to cast to `unknown` first?

Am I missing something here?

**Comment by marcolink** [comment]
Hi @yan-kisen 

The current output of this tool is not creating types for linked entries. All fields of type `Entry` are defined as such. 
If you want to transform fields of type `Entry` to `Link`, I suggest a typescript util type:

Here is a little example how this could look like: [Example](https://www.typescriptlang.org/play?#code/PTAEAsBdIBwZwFwgOYEtLgK4CMB0BjAewFtgiA7SAU0oDNMAbMwymyeh3AKzmGwcLZgxAIZxqAJ2CpyAEyoAPXLNyQ4AYgAyADgCMAKEgBPGFVABRShKMAeAGKoqDWXAB8oALygA3vtCg4I0QfP39QVFkEAMgJGWRQgF9Q2kdnOFAohycXfST9QxMzTRkAa08Q-0Dg3zDQY1MogHJi8hLGgBpQ-wZSgBVCpssYow6u8Mjo2PJkTv8kvPqi0qpZLLT7VJd3cpqwgG012QA5EWIzGVASqiNCWlBDuABdAH5MzbgDzZOzx9BFajk6SG1hsMloVAkoAAqu5nqAWmU3tkPodvlRHrl8osLFYjAiVg8Nsj3F5gbZ8at3kS0q5XPkCqZQABZIwPHahERRcRTeL+bBRciYYjYCGhfBRMk2bwJOl5CjiUDEIxkiW4mwsh4kioBIJRXb+CJRABEslocFNRsSs1AKWRerGnNARvATgERutfKiug9oHF2tqVXttVqhtAjV0ACYAMyNMZzH3+W1pDI+JK1NOgeb5eWQRXK3EAdXQ4ApD1Vw1LVI17y1u0D-vGxtN5tolvjyXeQbCjudrsI7rG-NA3rGfv1YXr49qPVa-QaYbJo2DYUWTQRS+XjbDkZjcczYwz8yAA)

**Comment by marcolink** [comment]
Closing this for now - might consider adding a custom renderer for this.
