### ISSUE TITLE
typeError: validations.map is not a function: linkContentType can be a string or a string[]

### ISSUE THREAD

**Issue by parkerhutchinson** [contentful-userland/cf-content-types-generator#148]
The validations are failing for me because it thinks that `linkContentType` can only be an array of string values. Wrong assumption `linkContentType` can be a string or an array of strings 

`LinkContentType: ['entryRef', 'entryRefTwo']`
or
`LinkContentType: 'entryRef'`

This may go against the official docs but it is allowed and is valid migration using contentfuls DSL.

**Comment by parkerhutchinson** [comment]
here is the migration that allows this to happen: 
```
page.createField('refField', {
    name: 'Ref Field,
    type: 'Array',
    required: true,
    items: {
      type: "Link",
      linkType: "Entry",
      validations: [{
        linkContentType: 'contentTypeId'
      }]
    }
  });
```

this will show as a string in the JSON output on the content type and be a valid link type.

**Comment by marcolink** [comment]
Hi @parkerhutchinson,

That sounds like a reasonable change! I'm currently pretty busy - would it be possible for you to create a PR for that?
