### ISSUE TITLE
Suggestions on how to do type narrowing?

### ISSUE THREAD

**Issue by laukondrup** [contentful-userland/cf-content-types-generator#151]
**This is just a question not directly tied to this library so feel very free to just close it.**

Do you have suggestions on how to do type narrowing?

```
export interface TypeBlogFields {
  component: Contentful.Entry<Button | Image | Link | Text | Video>;
}
```

```
const blog: TypeBlogFields = getBlog();
const isButton = blog.component.sys.contentType.id === 'button'
```

In my eyes then ideally `Sys` was generic such that the `contentTypeId` was a constant value instead of a `string`. Then, if you check `sys.contentType.id` with an if statement TypeScript would be able to do type narrowing.

Not sure if you know of a better way 😊

**Comment by ManAnRuck** [comment]
A lib which supports this, is https://github.com/intercom/contentful-typescript-codegen

**Comment by marcolink** [comment]
@ManAnRuck thanks for sharing, can you point me to the right place in the code, would like to see how it's done. 
I do have ideas on how it could be achieved with a custom render.
