### ISSUE TITLE
Union type shuffling

### ISSUE THREAD

**Issue by phawxby** [contentful-userland/cf-content-types-generator#155]
https://github.com/contentful-userland/cf-content-types-generator/blob/d026f76be6c05a0f8ab9d497ce94828e2342c3f5/src/renderer/generic/render-type-union.ts#L2

It probably makes sense to sort the union types pre-rendering so that it removes the chances of unnecessary shuffling.

**Comment by marcolink** [comment]
Hey @phawxby what do you mean by shuffling? does the order in a union can have an impact?

**Comment by phawxby** [comment]
> Hey @phawxby what do you mean by shuffling? does the order in a union can have an impact?

It doesn't directly, but it does in source control assuming you commit the output to your repo. If the union gets shuffled then it can be hard to tell what actually changed.

**Comment by marcolink** [comment]
@phawxby WOuld [this](https://github.com/contentful-userland/cf-content-types-generator/pull/156) solve the case?

**Comment by phawxby** [comment]
Yes, I have done the same thing in our highly customised fork. One of the things on the agenda is to see if the new overrides will allow us to ditch the customisations and get back on the core.

**Comment by marcolink** [comment]
@phawxby I'd be very interested if the custom renderer interface suits your needs - and if not - why not. specially since you're one of the most active persons on this project :)

**Comment by phawxby** [comment]
I will keep you updated. Thanks.
