### ISSUE TITLE
`import * as Contentful from "contentful";` produces error

### ISSUE THREAD

**Issue by AndrisBorbas** [contentful-userland/cf-content-types-generator#163]
`This import is never used as a value and must use 'import type' because 'importsNotUsedAsValues' is set to 'error'.ts(1371)`

In the generated files it should import contentful only as a type because if 'importsNotUsedAsValues' is set to error then it produces an error. 

Should be: `import type * as Contentful from "contentful";`

**Comment by marcolink** [comment]
Hi @AndrisBorbas, 

thanks for the callout - would you be able to create a PR for that?

**Comment by AndrisBorbas** [comment]
Hi, sorry for the late reply, just noticed it. I tried looking into the code, but I couldn't find where that line gets generated.

**Comment by marcolink** [comment]
Hi @AndrisBorbas 
I have re-worked they way imports are generated. The PR is currently in review, maybe we want to have a look. Any comments are welcome :) 

#205
