### ISSUE TITLE
Feature request: Customize file name

### ISSUE THREAD

**Issue by tatemz** [contentful-userland/cf-content-types-generator#164]
Currently, it is not possible to override the file name

Can the `moduleName`  function [used here](https://github.com/contentful-userland/cf-content-types-generator/blob/9431afc12f7ec651841d3b02d5ba462d953b089b/src/cf-definitions-builder.ts#L43) be from a `context` instead?

**Comment by marcolink** [comment]
Hi @tatemz 
What input would be relevant for you to compute a custom file name?

**Comment by marcolink** [comment]
closing this for now

**Comment by tatemz** [comment]
Hey so I came back to this and my team and I ended up doing exactly what you suggested by extending the renderer. We actually made two versions, one generated the TS, and another generated `runtypes` ([link](https://github.com/pelotom/runtypes)) configuration to ensure runtime validity for some of our models.

Thanks for a great tool!

**Comment by marcolink** [comment]
@tatemz This seems to be a pretty cool use case 😍 

Would you be interested to open a PR and add it to the project?

**Comment by marcolink** [comment]
@tatemz added a simple type-guard generator: https://github.com/contentful-userland/cf-content-types-generator/pull/226
