### ISSUE TITLE
Dev-only code pollutes production builds and causes warnings when installed using Yarn

### ISSUE THREAD

**Issue by wojtekmaj** [contentful-userland/cf-content-types-generator#170]
Binary has this bit of code:
```ts
const dev = fs.existsSync(project);

if (dev) {
    // eslint-disable-next-line node/no-unpublished-require
    require('ts-node').register({project});
}
```
which does not get stripped out from production build.

This causes `ts-node` to be installed alongside `cf-content-types-generator`, despite not being used at all in production

This, in turn, causes warnings when installed using Yarn:
```
➤ YN0000: ┌ Resolution step
➤ YN0002: │ cf-content-types-generator@npm:2.2.3 doesn't provide @types/node (pcdbc9), requested by ts-node
➤ YN0002: │ cf-content-types-generator@npm:2.2.3 doesn't provide typescript (pfffe7), requested by ts-node
➤ YN0000: │ Some peer dependencies are incorrectly met; run yarn explain peer-requirements <hash> for details, where <hash> is the six-letter p-prefixed code
➤ YN0000: └ Completed
```

Recommendations:
* Move `ts-node` to `devDependencies`
* Strip out any dev-only code from production builds

**Comment by marcolink** [comment]
> Strip out any dev-only code from production builds

I would assume moving `ts-node` to `devDependencies` should be sufficient. 
`tsc` is not looking into the bin folder to detect relevant depedencies 

what do you think?

**Comment by wojtekmaj** [comment]
Technically it will work because dev will be false on production, of course. Just thought you may want to have things all clean and separated. But user-facing issue with dependency warning is definitely resolved, can confirm that!

**Comment by marcolink** [comment]
@wojtekmaj applied your PR suggestion in the latest release!
