### ISSUE TITLE
Unable to use CLI

### ISSUE THREAD

**Issue by evolfo** [contentful-userland/cf-content-types-generator#181]
After npm installing the package, I'm unable to use the cli. I've restarted terminal and no luck.

`command not found: cf-content-types-generator`

**Comment by marcolink** [comment]
Hi @evolfo,

can you share a bit more details about your setup (and how you installed the CLI). Also, how exactly are you calling it?

**Comment by marcolink** [comment]
Currently not reproducible for me - closing for now.
