### ISSUE TITLE
TypeError: context.getFieldRenderer(...) is not a function

### ISSUE THREAD

**Issue by matulkum** [contentful-userland/cf-content-types-generator#198]
I am trying to generate types using the cli. I do not provide a JSON file but pass spaceId and token. This is the command I am using:
```
npx cf-content-types-generator --spaceId=XXX --token=XXX -o test-dir
```

This is the result:
```
  ✔ Initialize client (1s)
  ✔ Fetching data from space
    ✔ Connecting to space (1s)
    ✔ Fetching content types data (1s)
    ✔ Fetching tags data (1s)
    ↓ Fetching editor interfaces data [skipped]
    ↓ Fetching content entries data [skipped]
    ↓ Fetching assets data [skipped]
    ✔ Fetching locales data (1s)
    ↓ Fetching webhooks data [skipped]
    ↓ Fetching roles data [skipped]
  ↓ Download assets [skipped]
  ↓ Write export log file [skipped]
┌────────────────────┐
│ Exported entities  │
├───────────────┬────┤
│ Content Types │ 28 │
├───────────────┼────┤
│ Tags          │ 43 │
├───────────────┼────┤
│ Locales       │ 4  │
└───────────────┴────┘
The export took less than a minute (1s)
No errors or warnings occurred
The export was successful.
    TypeError: context.getFieldRenderer(...) is not a function
```

Nothing is written to disk.

**Comment by marcolink** [comment]
Hi @matulkum,
Could you provide a bit more information about your system and the version you're using?

**Comment by matulkum** [comment]
Sure.

These are the versions of the relevant modules I have in the `package.json`:
```
contentful: ^9.1.34
contentful-import: ^8.5.1
contentful-management: ^10.19.0
contentful-cli: ^1.19.1
cf-content-types-generator: ^2.4.2
```

My node version is `16.15.1` and I am on OSX version `13.0.1`.

**Comment by marcolink** [comment]
Hmmm, 

unfortunately, I'm not able to reproduce it.

**Comment by veu** [comment]
Sounds like the content types contain an unsupported field type. I get the same error when the content types contain a ResourceLink.

**Comment by marcolink** [comment]
@veu good catch! 
Would you be interested in opening a PR for a fix :)

**Comment by veu** [comment]
@matulkum Do you still see the error with the latest version?

**Comment by marcolink** [comment]
closing this for now due to inactivity
