### ISSUE TITLE
generated type guards can not be used when imported from index

### ISSUE THREAD

**Issue by kurkle** [contentful-userland/cf-content-types-generator#237]
With the `-g` flag, type guards are generated nicely. But they are exported as `type` in the index, which makes then not usable through the index:

```ts
export type { isTypeAsset, TypeAsset, TypeAssetFields } from "./TypeAsset";
```

When trying to use:

```
'isTypeAsset' cannot be used as a value because it was exported using 'export type'.ts(1362)
```

**Comment by marcolink** [comment]
Thanks @kurkle 🙏 

Would you mind reviewing this: https://github.com/contentful-userland/cf-content-types-generator/pull/239

**Comment by kurkle** [comment]
Sorry I was not fast enough for the review, but I can confirm it works fine now 👏
