### ISSUE TITLE
Request for LICENSE file

### ISSUE THREAD

**Issue by cutepig** [contentful-userland/cf-content-types-generator#252]
First of all, thanks for giving us the first and only type generator to support v10 types!

But as such, some projects (including one where I'm currently) have such license restrictions that the provided license should appear in a LICENSE file or otherwise it's a no-go, even though this project seems to be licensed under MIT based on the `package.json#license` field.

We would highly appreciate if you can add LICENSE file, so we could proceed in using your library in our project. Thanks!

**Comment by marcolink** [comment]
The file has been added!
