### ISSUE TITLE
"Type does not satisfy the constraint 'EntrySkeletonType'."

### ISSUE THREAD

**Issue by dtrenz** [contentful-userland/cf-content-types-generator#262]
When using generated types w/ `contentful: ^10.2.3` (using `cf-content-types-generator: ^2.12.2`):

```
Type '<Generated Type>' does not satisfy the constraint 'EntrySkeletonType'. 
Type '<Generated Type>' is missing the following properties from type 'EntrySkeletonType': fields, contentTypeId
```

**Comment by veu** [comment]
Hi, we do need a bit more info to help you out.
* What were you trying to do when you got the error?
* How does your setup look like? Especially, which flags were you using for the type generator?
* What does `<Generated Type>` look like?

**Comment by BernardHymmen** [comment]
I just ran into the exact same issue.  This is my first time trying to do type generation for Contentful objects so I was just gettting started and following the steps laid out in this very nice blog post

https://www.seancdavis.com/posts/generating-workable-typescript-types-from-contentful-content/

There's no date on that post (boo!), but it looks like the embedded video was uploaded in early May, FWIW.  Anyway, don't recall making any changes to what the post describes, other than consolidating it all into a single npm script like so:
````
    "contentful-export": "contentful space export --config contentful/export-config.json --management-token %CONTENTFUL_MANAGEMENT_PAT% --space-id %CONTENTFUL_SPACE_ID%",
    "contentful-typegen": "cf-content-types-generator contentful/export.json --out types/contentful",
    "contentful-update": "npm run contentful-export && npm run contentful-typegen"
````
Other than that, the post describes my setup and process accurately.  I've got a `pre-build.cmd` script that I run as part of my build to automatically update my Contentful models for both my C# and (hopefully soon) TypeScript types.  Here's the command for the TypeScript part of it:
````
call npm run contentful-update
````
This process generates a JSON schema file that looks just fine to my casual eye, and the TypeScript type definitions all look fine too...except for the red squiggles in VSCode on the type parameter in every instance of `Entry<T>` (and the lack of a `sys` property on my objects, but maybe that's expected).  Here's an example of one of my objects...
````
import type { Asset, Entry, EntryFields } from "contentful";
import type { TypePersonFields } from "./TypePerson";

export interface TypeBlogPostFields {
    title: EntryFields.Symbol;
    slug: EntryFields.Symbol;
    heroImage?: Asset;
    description: EntryFields.Text;
    body?: EntryFields.Text;
    author?: Entry<TypePersonFields>;  // <== squiggles on TypePersonFields
    publishDate: EntryFields.Date;
    project?: Entry<Record<string, any>>[];  // <== squiggles on Record<string, any>
}

export type TypeBlogPost = Entry<TypeBlogPostFields>; // <== squiggles on TypeBlogPostFields
````
All the error messages are versions of 

> Type 'TypePersonFields' does not satisfy the constraint 'EntrySkeletonType'.
  Type 'TypePersonFields' is missing the following properties from type 'EntrySkeletonType': fields, contentTypeIdts(2344)

Here are the various package versions I'm using:
````
dependencies
    "contentful": "^10.2.3",
    "contentful-cli": "^2.6.22",

devDependencies
    "cf-content-types-generator": "^2.12.2",
    "typescript": "^4.7.4"
````

**Comment by veu** [comment]
@BernardHymmen To generate types for v10 you need to add the `--v10` or `-X` option. That will create the new EntrySkeleton format and you’re good to go.

**Comment by SimonyanGrno** [comment]
@BernardHymmen I've used uppercase X and everything works fine

**Comment by marcolink** [comment]
This issue seems to be solved - will close for now
