### ISSUE TITLE
Type error after Contentful `10.0.0-beta-v10.32`

### ISSUE THREAD

**Issue by gergoradeczki** [contentful-userland/cf-content-types-generator#271]
10.0.0-beta-v10.32 is the last safe version in the v10 of the [Contentful](https://www.npmjs.com/package/contentful) package. After that, the generated files have the same type error:

```
... is missing the following properties from type 'EntrySkeletonType': fields, contentTypeId
```

**Comment by Hultner** [comment]
I also get similar errors related to EntrySkeletonType:

`Type 'TypeArticleFields' does not satisfy the constraint 'EntrySkeletonType'.`

**Comment by gergoradeczki** [comment]
Thanks for the notice, @nemanja-bulatovic-work. Turns out I completely missed that option in the docs.
