### ISSUE TITLE
Property does not exist on type {} | {}

### ISSUE THREAD

**Issue by sibin-sedlan-symphony** [contentful-userland/cf-content-types-generator#288]
I've recently tried upgrading the `contentful` library to version 10.6.1.
As a result, it seems like the `Entry` type has been changed to the point that all newly-generated types have the property field as a `{} | {}`, meaning that I cannot access any of the fields properties without casting each field prop as the approproate field type.
Is this a known issue, do you perhaps have an ETA on when it's going to be fixed?

Thanks in advance.

p.s. I'm attaching a screenshot with the typecheck error for clarity.
<img width="1115" alt="image" src="https://github.com/contentful-userland/cf-content-types-generator/assets/109209953/862666a6-9e06-4c62-b3bf-b320c28eb796">

`TypeStoryField` certainly has the `title` property as well as a few others but is inaccessible

<img width="394" alt="image" src="https://github.com/contentful-userland/cf-content-types-generator/assets/109209953/cc5ec89c-6efb-450e-b5a0-f309d086a2c5">

And this is from the automatically generated type

**Comment by marcolink** [comment]
Hey @sibin-sedlan-symphony, 

Did you generate the types with the `-X` [flag](https://github.com/contentful-userland/cf-content-types-generator#usage).
This is currently required to get the right types for `contentful@10`.

This will generate skeleton types for every content type. You can [use these Skeleton types as Generic type](https://github.com/contentful/contentful.js/blob/master/TYPESCRIPT.md#dynamic-field-query-keys) values when calling get Entries:

```ts
// your entries object will be typed correctly
const entries = await contentful.getEntries<TypeStorySkeleton>({content_type:'story'})
```

**Comment by sibin-sedlan-symphony** [comment]
It does seem to work, thanks for your help, don't know how I missed this.
