### ISSUE TITLE
Generated field interface does not satisfy the constraint 'EntrySkeletonType'

### ISSUE THREAD

**Issue by fireseasonnow** [contentful-userland/cf-content-types-generator#307]
I've generated field interface from the Contentful json export:
```
import type { Asset, Entry, EntryFields } from "contentful";

export interface TypeAuthorFields {
    firstName?: EntryFields.Symbol;
    lastName?: EntryFields.Symbol;
    img?: Asset;
    bornPlace?: EntryFields.Symbol;
    diedPlace?: EntryFields.Symbol;
    nationality?: EntryFields.Symbol;
    bornDate?: EntryFields.Symbol;
    diedDate?: EntryFields.Symbol;
    slug?: EntryFields.Symbol;
}

export type TypeAuthor = Entry<TypeAuthorFields>;
```
but `TypeAuthorFields` throws me an error in the last line:
```
Type 'TypeAuthorFields' does not satisfy the constraint 'EntrySkeletonType'.
Type 'TypeAuthorFields' is missing the following properties from type 'EntrySkeletonType': fields, contentTypeId
```

**Comment by marcolink** [comment]
Hi @fireseasonnow 👋 
Can you share the version of `contentful.js` you're using and the exact command you use to generate the types?

**Comment by fireseasonnow** [comment]
Sure, I'm using `contenful@10.6.5` and running `bunx cf-content-types-generator contentful-export.json -o types` using `bun@1.0.8`

**Comment by marcolink** [comment]
Happy to hear it also works with `bun` 😎 
In order to export types for the "not so new anymore" `contentful@10` client, you need to [provide](https://github.com/contentful-userland/cf-content-types-generator#usage) the `-X` flag. 
We will make this the default with the next major version.

**Comment by fireseasonnow** [comment]
My bad, I missed this flag. Now it generates types correctly. Then only problem I'm having though is when using GraphQL queries I'm requesting an image:
```
img {
    title
    url
    width
    height
}
```
but the type I'm having `img?: EntryFieldTypes.AssetLink;` shows that those properties don't exist on type 'AssetLink'.
Do you know how to approach this?

**Comment by marcolink** [comment]
@fireseasonnow this library generates types exclusively for the REST responses. Types returned by GraphQL can vary in shape.
