### ISSUE TITLE
Support EU Data Center

### ISSUE THREAD

**Issue by Swissbite** [contentful-userland/cf-content-types-generator#312]
Contentful added the support to host an organisation within the EU, see https://www.contentful.com/developers/docs/infrastructure/eu-data-residency/

Therefore, the endpoints for the API in EU changed:

API | URL
-- | --
Content Management API | https://api.eu.contentful.com
Content Delivery API | https://cdn.eu.contentful.com
Content Preview API | https://preview.eu.contentful.com
GraphQL API | https://graphql.eu.contentful.com
Images API | https://images.eu.ctfassets.net
User Management API | https://api.eu.contentful.com

Suggestion:
- Add an additional and optional flag where the endpoint is in "EU" or not.

Alternative:
- Option to overwrite the host itself, as it is defined in the `contentful-export` library, see https://github.com/contentful/contentful-export#host-string-default-apicontentfulcom

**Comment by marcolink** [comment]
@Swissbite would [that](https://github.com/contentful-userland/cf-content-types-generator/pull/325) solve the issue?

**Comment by Swissbite** [comment]
@marcolink Yes, I can confirm that the solution with #325 will solve the issue.
