### ISSUE TITLE
Release a new version with updated contentful and allow minor version differences if possible

### ISSUE THREAD

**Issue by restfulhead** [contentful-userland/cf-content-types-generator#315]
Contentful up to version `10.3.7` has the following vulnurability: Axios Cross-Site Request Forgery Vulnerability - https://github.com/advisories/GHSA-wf5p-g6vw-rhxx

I can see a patch [was committed here](https://github.com/contentful-userland/cf-content-types-generator/commit/1f2e8526bacffd5e668d31494cdd4133f83b7e23). Can you please release a new version of this library with the fix?

This wouldn't be necessary, if the dependency wasn't pinned to a specific version. Please consider allowing minor or at least patch version differences (i.e. `^10.6.1` or `~10.6.1`). This way we can run `npm audit fix` and a new release is not needed.

**Comment by marcolink** [comment]
Done
