### ISSUE TITLE
Type Not Satisfying Entry Requirements

### ISSUE THREAD

**Issue by KyleMo** [contentful-userland/cf-content-types-generator#321]
I've ran the scripts and all my types seem to have successfully generated and look correct. However, in my content model types file I am getting the follow error. This error is occurring on every model. As a result of this error, the `fields` property doesn't appear to be getting the typings.

```
Type 'TypeBlogPostFields' does not satisfy the constraint 'EntrySkeletonType<FieldsType, string>'.
  Type 'TypeBlogPostFields' is missing the following properties from type 'EntrySkeletonType<FieldsType, string>': fields, contentTypeId
```

For more context, here is the entire file

```
import type { Entry, EntryFields } from 'contentful'

export interface TypeBlogPostFields {
    title?: EntryFields.Symbol
    slug: EntryFields.Symbol
    content: EntryFields.Text
}

export type TypeBlogPost = Entry<TypeBlogPostFields>
```

**Comment by marcolink** [comment]
Hey @KyleMo,
What [flags](https://github.com/contentful-userland/cf-content-types-generator?tab=readme-ov-file#usage) you use to generate your types, and what version of [contentful](https://github.com/contentful/contentful.js) are you using?

**Comment by KyleMo** [comment]
@marcolink  This is the script I use to generate types `cf-content-types-generator src/contentful/export.json --out src/types/contentful`

Contentful version: ^10.6.14

**Comment by marcolink** [comment]
If you use the v10 client, you have to provide the `--v10` flag.

**Comment by KyleMo** [comment]
Thank you so much! That seemed to fix it!

**Comment by Twister42** [comment]
I know this is closed, but maybe this should be written bigger somewher in the docs ?

**Comment by marcolink** [comment]
@Twister42 the next major version will likely only support v10. But please feel free to create a PR to nake the flag more prominent.
