### ISSUE TITLE
Why can `EntryFieldTypes.Array<EntryFieldTypes.EntryLink<EntrySkeletonType>>` array include `undefined`?

### ISSUE THREAD

**Issue by Shintarot** [contentful-userland/cf-content-types-generator#331]
## Environment
```
VSCode 1.87.2 (Universal) on Darwin x64 21.6.0
"typescript": "^5.4.2",
"@types/node": "^20.11.28",
"contentful": "^10.8.1",
"contentful-cli": "^3.1.44",
"cf-content-types-generator": "^2.15.0",

cf-content-types-generator -X -s ${CONTENTFUL_SPACE_ID}  -t ${cmaToken} -o ${outDir}
```
## Actual Behavior
There is a `References, many` field in the configuration pictured below.

![app contentful com_spaces_mxid377r9ws5_content_types_report_fields](https://github.com/contentful-userland/cf-content-types-generator/assets/39514220/2e23c1be-30e5-4e31-a9a7-b04b240d0de7)
![app contentful com_spaces_mxid377r9ws5_content_types_report_fields (1)](https://github.com/contentful-userland/cf-content-types-generator/assets/39514220/378722a2-4659-4037-af1a-88812cff2b71)

The type of this field is defined as `EntryFieldTypes.Array<EntryFieldTypes.EntryLink<TypeXXXXSkeleton>` (`TypeXXXXSkeleton` is my custom type.).

According to the editor, this type is actually `(TypeXXXX | undefined)[]`.

Why can't it be `TypeXXXX[]`?

## Possible reason
When the Entry specified in `References, many` is missing (deleted), Contentful returns `undefined` in the array?

## Expected Behavior
If the referenced Entry does not exist, it is a problem on the source side (an Entry that does not exist should not be able to be referenced), so I think it should not be included in the array.

`References, many` field should not be typed as `(TypeXXXX | undefined)[]` but `TypeXXXX[]`.

**Comment by ryancooper7** [comment]
I agree with this. I believe I posted the same [issue](https://github.com/contentful/contentful.js/issues/2216) on the contentful.js ghitub page

**Comment by veu** [comment]
Your possible reason is correct. This is intended behavior to be able to tell which entries in the list could be resolved.
