### ISSUE TITLE
ResponseTypeRenderer is not exported

### ISSUE THREAD

**Issue by ryancooper7** [contentful-userland/cf-content-types-generator#348]
`ResponseTypeRenderer` is not exported from `src/renderer/type/index.ts`

**Comment by marcolink** [comment]
@ryancooper7 thanks for reporting this, would you be able to open a PR for it?

**Comment by ryancooper7** [comment]
Yes I can do that!

**Comment by ryancooper7** [comment]
https://github.com/contentful-userland/cf-content-types-generator/pull/349

**Comment by marcolink** [comment]
fixed with `2.15.2`
