### ISSUE TITLE
Generated types are not compatible with `withAllLocales`

### ISSUE THREAD

**Issue by tgarv** [contentful-userland/cf-content-types-generator#359]
I've used `npx cf-content-types-generator -t <token> -s <space> -X -o /types/codegen-types` to generate types for my Contentful space. The main type I'm trying to fetch is called `JurisdictionConfig`, so I'm using the following code to fetch an entry of that type:

```typescript
const entryResponse: TypeJurisdictionConfig<'WITH_ALL_LOCALES'> = await client.withAllLocales.getEntry<
  TypeJurisdictionConfig<'WITH_ALL_LOCALES'>
>(entryId);

const entryFields: TypeJurisdictionConfigFields = entryResponse.fields;
```

On the `entryFields` line, I get the TypeScript error:
```
Types of property 'stateName' are incompatible.
    Type '{ [x: string]: string | undefined; }' is missing the following properties from type 'Symbol<string>': type, values
```

So, inspecting the TypeJurisdictionConfigFields interface, I see `stateName: EntryFieldTypes.Symbol;`. Every field is essentially just a Symbol, not the map from Locale to value that you would expect when fetching with the `withAllLocales` modifier.

Is there something I've done wrong in my implementation, or does this library not support this use case?

**Comment by marcolink** [comment]
hey @tgarv,

here is an example for different response modifiers: https://codesandbox.io/p/sandbox/contentful-cda-rest-client-typescript-5ftx3d?file=%2Fsrc%2Findex.ts%3A16%2C34

**Comment by marcolink** [comment]
will close this for now.
